### ISSUE TITLE
Error: LoadVDDisplayInfo: could not get current display number: GetVDDisplayNumber: could not get current display number: The type initializer for 'DesktopManager' threw an exception.

### ISSUE THREAD

**Issue by dadajason** [dankrusi/WindowsVirtualDesktopHelper#10]
LoadVDDisplayInfo: could not get current display number: GetVDDisplayNumber: could not get current display number: The type initializer for 'DesktopManager' threw an exception.
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

GetVDDisplayNumber: could not get current display number: The type initializer for 'DesktopManager' threw an exception.
   at WindowsVirtualDesktopHelper.App.GetVDDisplayNumber(Boolean throwException)
   at WindowsVirtualDesktopHelper.App.LoadVDDisplayInfo()

Windows Build: 21996
Windows Virtual Desktop Helper Version: 1.6.0.0
Virtual Desktop Implementation: VirtualDesktopWin10

**Comment by dankrusi** [comment]
Hi, thanks for the bug report. This Windows build 21996 is a leaked beta build of Windows 11. Its not an official Windows release. I will see if I can support this somehow, by altering the algorithm to detect the implementation to use. However if the standard Windows 11 implementation doesn't work I will close the ticket, as it would be really hard to create compatibility for such unofficial Windows versions.

**Comment by dankrusi** [comment]
Hi @dadajason, does this work for you?
[Setup.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/10193443/Setup.zip)

**Comment by dankrusi** [comment]
@dadajason any news?
