### ISSUE TITLE
Emoji compatibility for deskop name initials

### ISSUE THREAD

**Issue by tc-tommo** [dankrusi/WindowsVirtualDesktopHelper#106]
Hello, I think it would be great to add emoji support in the desktop name initial tray icon.

this would let the user name their desktops like:

💼 Work
🌐 Browsing
...

and the tray icon would display a little 💼 or 🌐 which would be fun & also more descriptive

currently it displays a tofu char ▯ (see screenshot)
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/59585282/92872df3-17e6-45b4-bf0d-8792a1f8cad5)

**Comment by dankrusi** [comment]
Will be in next version 1.16. Best, -dan

**Comment by dankrusi** [comment]
(Windows 11 only)
