### ISSUE TITLE
Taskbar icon not showing outside

### ISSUE THREAD

**Issue by chrisonline** [dankrusi/WindowsVirtualDesktopHelper#108]
I have enabled that the Windows Virtual Desktop Helper should show the icon outside in the taskbar, but it is still inside the arrow and not outside.

Have tried to reinstall and reboot but without success.

![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/2077218/a7e914d3-e8af-4343-8be4-290df19323f2)

Using latest version of the program.

Windows version:
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/2077218/67ae4bdf-b08a-497f-92b8-1f769ba40646)

**Comment by chrisonline** [comment]
Fixed it.
The program "Windows Virtual Desktop Helper" is listed multiple times inside the taskbar settings.
I have now enable the correct one and it is now again be shown.

How can I remove the other ones? And why are they listed multiple times?

![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/2077218/5eee0da0-fd60-4aad-ba44-296ec41799c6)

**Comment by dankrusi** [comment]
The windows API only allows for regular icons with a regular square size, unless you use unofficial APIs. The way WVDH works, is that it sets multiple different icons for the functionality (see the README). 

You can disable the ones you don't want by dragging them to the overflow tray or disabling them from the WVDH settings.
