### ISSUE TITLE
FR: Adding Font Options

### ISSUE THREAD

**Issue by IGRACH** [dankrusi/WindowsVirtualDesktopHelper#11]
This is great little program, exactly what I needed. Only thing that is missing is option to set font, font-face and size of the number in the taskbar. It would be great if you can add that option xD

**Comment by dankrusi** [comment]
That would be cool, but it would require that I generate the little icons dynamically in runtime. I want to keep the app as slim and lightweight as possible, so not sure if I will add this. I will look into it.

**Comment by IGRACH** [comment]
Thanks for the replay xD. 

You don't have to add whole fond support. I was more thinking of a bit smaller icons. Current icon is pretty big if you use small taskbar icons. You could add lets say a couple of different sizes of icons. Maybe small, medium, large; standard, bold.

**Comment by dankrusi** [comment]
@IGRACH , can you send me a screenshot of how mean the icons are a bit big for the latest version?

**Comment by dankrusi** [comment]
This is possible in v2.0 - see https://github.com/dankrusi/WindowsVirtualDesktopHelper/blob/main/Documentation/Settings.md for all the configurations.
