### ISSUE TITLE
[Feature Request]: Show count of desktops with current desktop number in tray icon

### ISSUE THREAD

**Issue by avenmore** [dankrusi/WindowsVirtualDesktopHelper#110]
### What happened?

I see "1" in my tray, but don't know if I have created any other desktops yet, or I create a new one without realising that I created one earlier for this purpose, so now have three and get confused when I switch to one that is suddenly empty.

Suggest an option to show the total count of desktops along with the number of the current desktop in the tray icon, e.g. "1/1", "1/2", "2/3", etc.

(if this issue has the label "bug", it's because this was the only kind of issue I was able to create and wasn't able to remove it).

### WVDH Version

1.14

### Windows Version

Windows 10 x64

**Comment by dankrusi** [comment]
@avenmore, the desktop tray icons are so small, it's not really possible to show 3 digits... I am going to close this issue until others request it again. Best, -dan

**Comment by dankrusi** [comment]
Okay great. The idea of the app is to keep as simple and universal as possible and focus on Windows compatibility instead, so I am reluctant to add too many features. The plan is in the future to add a layer of configuration, which users can freely change using config files to support such things (like a setting NumberIconText: "{desktop-number}/{total-desktops}"....

**Comment by avenmore** [comment]
Sorry, don't want to be an annoyance, just wanted to show that, with a bit more tweaking, it is possible to get decently readable numbers into that icon.
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/13959411/de4d21da-6c1a-4988-87da-f0c9e3008ad9)
