### ISSUE TITLE
[Bug]: Unable to get the Tray Icon out of the overflow menu

### ISSUE THREAD

**Issue by vadjle** [dankrusi/WindowsVirtualDesktopHelper#113]
### What happened?

When enabling the Windows Virtual Desktop Helper tray icons in the Windows Settings.  Only the Previous and Next Desktop Icons are visible in the system tray.

After a reboot the option for the tray icon indicator in the Windows Settings is toggled off again.  Toggling it back on does not resolve the issue.

![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/70152576/e6eb1203-c2e8-4f23-872b-5fa2a233356b)

![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/70152576/09851663-a2e6-4cbc-a346-9eb620756cbd)

### WVDH Version

1.14

### Windows Version

Windows 11 21H2 Build 22000.2416

**Comment by dankrusi** [comment]
Hi @vadjle , are you sure its not just hidden in the expand menu? Best, -dan

**Comment by dankrusi** [comment]
Okay thanks - my feeling is that Windows 11 uses not the ID of the icon, but the tooltip/name of the icon. The number icon changes the tooltip I believe. I will send you a test version so that you can confirm if that solves it.

**Comment by dankrusi** [comment]
[WindowsVirtualDesktopHelper Executable v1.15.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/12877467/WindowsVirtualDesktopHelper.Executable.v1.15.zip)

**Comment by vadjle** [comment]
Hi @dankrusi , thank you for the test version.  This has resolved the issue.

**Comment by dankrusi** [comment]
Great thnx.
