### ISSUE TITLE
[Feature request]: new built in desktop number overlay

### ISSUE THREAD

**Issue by Michael-Steshenko** [dankrusi/WindowsVirtualDesktopHelper#116]
### What happened?

New windows update "windows 11 moment 4 - KB5031354", has a new overlay showing the desktop number similar to this project, except there are no options to modify or remove it.
I think, if possible, adding an option to disable the built in windows overlay would be great for this project.

### WVDH Version

1.14

### Windows Version

Windows 11 22H2 build 22621.2428

**Comment by dankrusi** [comment]
Hi @Michael-Steshenko , shouldn't this feature be provided by Microsoft instead? Is it even possible to disable it? If you can find a registry key to change the MS behavior, I can add it. But it needs to be a official API or feature, otherwise it will keep breaking... Best, -dan

**Comment by dankrusi** [comment]
Also, can you send me a screenshot of the MS version?

**Comment by Michael-Steshenko** [comment]
It definitely should be fixed by MS, but I doubt they will, they rolled this out without an option to reverse the update, or disable their version.
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/19752384/4d4532ef-6349-4f78-9fcd-778ff7ac71ae)
I don't have a registry key unfortunately.

**Comment by dankrusi** [comment]
If you keep an out for a registry key option (for example use Google Alerts), I will build this into the UI of WVDH. Let me know if it appears. Best, -dan
