### ISSUE TITLE
[Bug]: Setting "Show Overlay when switching desktop" is not saved

### ISSUE THREAD

**Issue by chrisonline** [dankrusi/WindowsVirtualDesktopHelper#117]
### What happened?

I disable the setting "Show overly when switching desktop", but after a restart of Windows this setting is again ON.

![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/2077218/467a6f50-3a4f-48c2-aafa-a3a7bc443f94)

### WVDH Version

1.14

### Windows Version

Windows 11 22H2 Build 22621.2428

**Comment by dankrusi** [comment]
@chrisonline I see - but it must be all the settings are not saving right? Are your running the app from the ZIP file, or installer?

**Comment by chrisonline** [comment]
@dankrusi Running it from installer. Have not tried the other settings yet. Should I try it?

**Comment by dankrusi** [comment]
Yes that would be helpful to figure out what is going on....

**Comment by chrisonline** [comment]
Yes all settings are not saved. Is there any log file I can send you?

This is the config file in the install folder:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
      <section name="WindowsVirtualDesktopHelper.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
    </sectionGroup>
  </configSections>
  <System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAwareness" value="PerMonitorV2" />
  </System.Windows.Forms.ApplicationConfigurationSection>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2"/>
  </startup>
  <userSettings>
    <WindowsVirtualDesktopHelper.Properties.Settings>
      <setting name="ShowPrevNextIcons" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="StartupWithWindows" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="ShowOverlay" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="OverlayAnimate" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="OverlayTranslucent" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="ClickDesktopNumberOpensTaskView" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="OverlayDuration" serializeAs="String">
        <value>medium</value>
      </setting>
      <setting name="OverlayPosition" serializeAs="String">
        <value>middlecenter</value>
      </setting>
    </WindowsVirtualDesktopHelper.Properties.Settings>
  </userSettings>
</configuration>

```
Change date in file explorer is 16.05. at 08:15, so it seems it does not update this file:
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/2077218/fe84803a-66d6-4c96-b3a7-d194550b45a3)

**Comment by dankrusi** [comment]
Your user settings should be saved in %userprofile%\appdata\local\Dan_Krusi - do you have config files there?

**Comment by chrisonline** [comment]
I use now the 1.15 you have released for a few minutes.

Yes there is a config file.

Current value is set to "false" for ShowOverlay in the settings file.

Now I set ShowOverlay to "true" via the Settings GUI and I check the settings file and the "ShowOverlay" is also "true":
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <WindowsVirtualDesktopHelper.Properties.Settings>
            <setting name="ShowPrevNextIcons" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="StartupWithWindows" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="ShowOverlay" serializeAs="String">
                <value>True</value>
            </setting>
```
I close the program and recheck the settings file and it is **still true**.
Now I start the program again and the settings file is changed to "false" for "ShowOverlay" immediately after start:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <WindowsVirtualDesktopHelper.Properties.Settings>
            <setting name="ShowPrevNextIcons" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="StartupWithWindows" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="ShowOverlay" serializeAs="String">
                <value>False</value>
            </setting>
```

So it seems that the start of the program rewrites the default settings?

**Comment by dankrusi** [comment]
Thanks for the investigation!

Hmmm so strange. I use the built in Microsoft .net settings stuff - but it seems its totally over engineered and incomprehensible how it works exactly. I double checked everything - I am loading and saving the values correctly. Can you just try uninstalling and deleting everything, and then re-installing? If other uses have this issue as well I will just write my own settings loader/saver...

**Comment by dankrusi** [comment]
Wait - found a MS bug that might be relevant. Does this solve the issue?
[WindowsVirtualDesktopHelper Executable v1.15.zip](https://github.com/dankrusi/WindowsV
[WindowsVirtualDesktopHelper Setup v1.15.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/13052631/WindowsVirtualDesktopHelper.Setup.v1.15.zip)
irtualDesktopHelper/files/13052629/WindowsVirtualDesktopHelper.Executable.v1.15.zip)

**Comment by chrisonline** [comment]
Too late. I have already done a complete deinstall and manually removed the folder "%userprofile%\appdata\local\Dan_Krusi" and the folder inside C:\Program Files (x86)!

After reinstall it is now working and the settings are correct saved.

**Comment by dankrusi** [comment]
Okay thanks. I will close the issue now.
