### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DavidRivera** [dankrusi/WindowsVirtualDesktopHelper#118]
### What happened?

I'm this error warning:

VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22621
Windows Release: 2009
Windows Product: Windows 10 Home
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.10.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_22H2

Log:
GetImplementationForOS: Windows Build Version: 22621
GetImplementationForOS: Detected Windows 11 22H2 due to build >= 22621
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10

### WVDH Version

Windows Virtual Desktop Helper Version: 1.10.0.0

### Windows Version

Windows 11 version 22H2 Windows Build: 22621

### Relevant log output

```shell
Log:
GetImplementationForOS: Windows Build Version: 22621
GetImplementationForOS: Detected Windows 11 22H2 due to build >= 22621
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by dankrusi** [comment]
please update to the latest version first - thanks!

**Comment by DavidRivera** [comment]
I did and it worked. Thank you.
