### ISSUE TITLE
Error: LoadVDDisplayInfo: could not get current display number: GetVDDisplayNumber: could not get current display number: The type initializer for 'DesktopManager' threw an exception.

### ISSUE THREAD

**Issue by yogalb** [dankrusi/WindowsVirtualDesktopHelper#12]
LoadVDDisplayInfo: could not get current display number: GetVDDisplayNumber: could not get current display number: The type initializer for 'DesktopManager' threw an exception.
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

GetVDDisplayNumber: could not get current display number: The type initializer for 'DesktopManager' threw an exception.
   at WindowsVirtualDesktopHelper.App.GetVDDisplayNumber(Boolean throwException)
   at WindowsVirtualDesktopHelper.App.LoadVDDisplayInfo()

Windows Build: 22000
Windows Virtual Desktop Helper Version: 1.6.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_21H2

**Comment by yogalb** [comment]
Thank you very much for developing and support this useful application.

**Comment by dankrusi** [comment]
Hi @yogalb, sorry for your troubles. Microsoft has created a bit of a mess regarding the virtual desktop API. Is there anything special with your Windows version? Give this version (
[WindowsVirtualDesktopHelper.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/10257468/WindowsVirtualDesktopHelper.zip)
) a try and let me know if that works.

**Comment by yogalb** [comment]
Hello Dankrusi,
You are right, Microsoft is a huge mess. There is nothing special about my Windows environment, always keeping updated.
(1)I think the reported bug showed up when I started to use VirtualBox. (2)Another reason I guess is after recovery from hibernation.
Thank you for your response.
Blagoy.
Dec. 19, 2022
8:31 a.m. (-5 GMT)
Mississauga, ON
Canada.
=================================================================================
    On Monday, December 19, 2022 at 03:25:28 AM EST, Dan Krusi ***@***.***> wrote:  
 
 


Hi @yogalb, sorry for your troubles. Microsoft has created a bit of a mess regarding the virtual desktop API. Is there anything special with your Windows version? Give this version (
WindowsVirtualDesktopHelper.zip
) a try and let me know if that works.

**Comment by dankrusi** [comment]
@yogalb ah okay, so it works usually, but crashes at some point?

**Comment by dankrusi** [comment]
@yogalb Give 1.7 a try, I added exception handling around the main monitor loop. Let me know if that works better for you.

**Comment by yogalb** [comment]
Hello Dan,
For sure I will give a try.For now I created a restart batch.Again your app is very usefull. I am wirking with min. 4 virtual desktop and your app make big difference!
Thank you.
Blagoy.
Dec. 20, 20222:27 p.m. (-5 GMT)Mississauga, ONCanada.

    On Tuesday, December 20, 2022 at 01:55:46 PM EST, Dan Krusi ***@***.***> wrote:  
 
 


@yogalb Give 1.7 a try, I added exception handling around the main monitor loop. Let me know if that works better for you.

**Comment by yogalb** [comment]
Hello Dankrusi,

WindowsVirtualDesktopHelper v.1.7 is better, but on rare occasions the taskbar desktop counter is not pointing to the right desktop.
I like your application and use it actively. Blagoy.
Dec. 27, 2022
1:44 p.m. (-5 GMT)
Mississauga, ON
Canada.
==========================================================================================
v.1.7 is better and more stable, but on rear cases the desktop conter is not pointing to the right desktop.



    On Tuesday, December 20, 2022 at 01:55:46 PM EST, Dan Krusi ***@***.***> wrote:  
 
 


@yogalb Give 1.7 a try, I added exception handling around the main monitor loop. Let me know if that works better for you.

**Comment by dankrusi** [comment]
Hmmm thats strange. The way the app works is actually by pining the desktop number every 100ms, and detecting a change there. This way I don't rely on any hooks into Windows etc... So it should be very reliable. Maybe there is a Windows issue which has been solved in 22H2? Let me know if you have any ideas what the issue might be. Best, -dan

**Comment by yogalb** [comment]
Hello,

First I would like to thank you for the app, it is very useful. The app is pretty stable, but I noticed on rare occasions it gets out of synchron. My guess is that the app has stopped working (the app loop 100 ms is dead).

Jan. 20, 2023
8:04 a.m. (-5 GMT)
Mississauga, ON
Canada.

**Comment by dankrusi** [comment]
Can you provide a log of the app console output?
