### ISSUE TITLE
[Feature Request]: Individual wallpapers for each screen in a multi-monitor environment

### ISSUE THREAD

**Issue by neotpravlennoye** [dankrusi/WindowsVirtualDesktopHelper#120]
### What feature?

Without VirtualDesk, windows allows users to set wallpaper for each screen individually, but when VirtualDesk is enabled, you can only set wallpaper for VirtualDesk, so that all screens under one VirtualDesk can only use the same wallpaper.
The feature I would like is to still be able to set the wallpaper for each screen individually when VirtualDesk is enabled.

### Windows Version

windows 11

**Comment by dankrusi** [comment]
Shouldn't you file this at Virtual Desk? I don't see how WVDH should provide features for Virtual Desk... Best, -dan
