### ISSUE TITLE
Windows Explorer crash while jumping to the inexistent virtual desktop

### ISSUE THREAD

**Issue by usernamelectro** [dankrusi/WindowsVirtualDesktopHelper#121]
### What happened?

Windows Explorer crashes every time I accidentally press the hotkeys + number of the virtual desktop that is not existant.

For example I am using 5 virtual desktops, sometimes I'm mistakingly press Ctrl+Alt+6 instead of Ctrl+Alt+5 which is followed by the delay in cursor movement, than Windows Explorer crashes and recovers afterwards.

### WVDH Version

1.15

### Windows Version

Windows 11 23H2 Build 22631.2715

**Comment by dankrusi** [comment]
Hi @usernamelectro , sorry thanks yes I can imagine this is a bug - will fix soon.
