### ISSUE TITLE
Orange flashing taskbar icons

### ISSUE THREAD

**Issue by ryan-hanson** [dankrusi/WindowsVirtualDesktopHelper#123]
### What happened?

When switching between desktops, the taskbar icons for active apps routinely flash orange 7 times, as if something within the app has changed and is trying to grab my attention.

Only happens while using ALT+#, ALT-CTRL+#, etc. I cannot duplicate the issue by using the arrows in systray. Also, this behavior does not occur when using the default Windows hotkey to switch one at a time (CTRL-WIN-arrow). 

I assume it's caused by switching between desktops too quickly.

I've tried disabling the behavior completely in RegEdit, with no luck.

### WVDH Version

1.15

### Windows Version

Windows 10

**Comment by dankrusi** [comment]
Why don't you just disable that feature in the settings, if its not working for you? Are you sure its not some other software you have added creating the issue?

**Comment by ryan-hanson** [comment]
> Why don't you just disable that feature in the settings, if its not working for you? Are you sure its not some other software you have added creating the issue?

I tried disabling the feature completely in RegEdit with all combinations of the values below, rebooting after each change, but none seemed to help. Looks like there's a way to disable via GUI in Windows 11 but not Windows 10.

HKEY_CURRENT_USER\Control panel\Desktop > ForegroundFlashCount = 1
HKEY_CURRENT_USER\Control panel\Desktop > ForegroundFlashCount = 0
HKEY_CURRENT_USER\Control panel\Desktop > ForegroundLockTimeout = 1
HKEY_CURRENT_USER\Control panel\Desktop > ForegroundLockTimeout = 0

Before I found your tool, I created an AutoHotKey script to switch desktops using Alt-#, but the scrolling animation between desktops was annoying and slow. Only good part was this issue did not exist, which is why I'm guessing the increased speed might somehow be causing it. Nonetheless, your solution is still much much better and I thank you for sharing it.

**Comment by dankrusi** [comment]
I meant in the settings of WVDH - disable the ALT+#, ALT-CTRL+#, etc feature... But I think you are confused as to what is doing what on your computer. WVDH just uses the Windows APIs, its not a custom implementation. So if something is broken or flashing strange, then its something you have configured on your system, either through a Windows feature or some other software you have installed...
