### ISSUE TITLE
KEYMAPS

### ISSUE THREAD

**Issue by darianmorat** [dankrusi/WindowsVirtualDesktopHelper#125]
### What feature?

I would like to be able to set up my shortcuts, I use **alt + num** for VSCODE tabs, and I just use 3 VD on windows, so I would like to be able to set up a shorcut for **alt + i,o,p** for the 3 VD

### Windows Version

Windows 11

**Comment by padd1er** [comment]
I second this.

For my case, I have more than 10 VDs and default shortcuts just aint enough.
Used to use Alt+Num for VDs 1-10 and Ctrl+Alt+Num for another five VDs (11-15)

**Comment by dankrusi** [comment]
This is coming...

**Comment by dankrusi** [comment]
@dankrusi The new configs for this will be:

```
hotkeys.myCustomKey1: "Alt + I = Desktop1"
hotkeys.myCustomKey2: "Alt + O = Desktop2"
hotkeys.myCustomKey3: "Alt + P = Desktop3"
hotkeys.myCustomKey4: "Ctrl + Alt + Left = DesktopLeft"
etc
```

**Comment by dankrusi** [comment]
See v2.0 - has this feature

https://github.com/dankrusi/WindowsVirtualDesktopHelper/blob/main/Documentation/Hotkeys.md

**Comment by dankrusi** [comment]
@davidfregoli thanks - have updated the docs slightly.
