### ISSUE TITLE
Error: LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10

### ISSUE THREAD

**Issue by StalkDe** [dankrusi/WindowsVirtualDesktopHelper#13]
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 25267
Windows Release: 2009
Windows Product: Windows 10 Home
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.7.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_22H2

Log:
GetImplementationForOS: Windows Build Version: 25267
GetImplementationForOS: Detected Windows 11 22H2 due to build >= 22621
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10

**Comment by dankrusi** [comment]
Hi @StalkDe , I manged to find some time to install a VM with this version of Windows, and have released 1.8 which should work for you. Best, -dan
