### ISSUE TITLE
[Bug]: Failed to start

### ISSUE THREAD

**Issue by zzz2496** [dankrusi/WindowsVirtualDesktopHelper#131]
### What happened?

Just installed the update and run it for the first time after update, it crashed.

### WVDH Version

1.15

### Windows Version

win11 22h2

### Relevant log output

```shell
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_23H2,VirtualDesktopWin11_InsiderCanary,VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22621
Windows Release: 2009
Windows Product: Windows 10 Home Single Language
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.15.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22621
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_InsiderCanary
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_InsiderCanary...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_InsiderCanary
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by dankrusi** [comment]
Does this version work for you? 
[WindowsVirtualDesktopHelper Executable v1.16.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/14061698/WindowsVirtualDesktopHelper.Executable.v1.16.zip)

**Comment by alejandrogonzalez01** [comment]
> Does this version work for you?
> 
> [WindowsVirtualDesktopHelper Executable v1.16.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/14065321/WindowsVirtualDesktopHelper.Executable.v1.16.zip)

This version is now working for me. Thank you!
Here are my Windows Specs

Edition	Windows 11 Business
Version	23H2
OS build	22631.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by Toshinori-Hayashi** [comment]
> Does this version work for you?
> 
> [WindowsVirtualDesktopHelper Executable v1.16.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/14065321/WindowsVirtualDesktopHelper.Executable.v1.16.zip)

I was having the same issue and this version resolved it.
Thank you!!

my windows spec
-- 
Edition	Windows 11 Pro
Version	23H2
OS build	22631.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by Tarpal** [comment]
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/11710753/08032e60-c418-4e90-9c9d-f5a2200d522f)

Win11 Pro
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/11710753/12522bc1-4ae0-4300-98f9-d954c1d6a065)

**Comment by zzz2496** [comment]
v1.16 still does not work for me. 
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/40851748/3fa462f9-dd45-41b8-93c4-8d2b3319227c)

Here's the complete error message:

Oh no! It seems your version of Windows is not yet supported! This is most likely due to your Windows Version being a Insider/Canary build, or a having a new patch where the APIs have changed. You can report the issue, but please be patient as it's a lot of work to keep up with all the Windows versions! 
Error: No implementation loaded successfully, tried: VirtualDesktopWin11_23H2, VirtualDesktopWin11_Insider25314, VirtualDesktopWin11_Insider22631, VirtualDesktopWin11_Insider, VirtualDesktopWin11_22H2, VirtualDesktopWin11_21H2, VirtualDesktopWin10 (LoadImplementationWithFallback)
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22621
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.16.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
Using config file: C:\Users\damir\AppData\Local\Temp\7zO8B20E07E\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22621
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider25314
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider25314...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider25314
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider22631
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider22631...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider22631
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10

**Comment by ChadThomsen** [comment]
I am seeing the exact same error after a recent Windows 11 patch update.

**Comment by dankrusi** [comment]
Thank you all for the bug reporting and help testing - please see the new official release v1.16: https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/tag/v1.16. This issue will be closed for now to avoid confusion - please open a new issue with your exact Windows version if you encounter problems.
