### ISSUE TITLE
[Feature Request]: Add a hotkey to switch to the most recent desktop

### ISSUE THREAD

**Issue by SaifMasoud** [dankrusi/WindowsVirtualDesktopHelper#134]
### What feature?

Since the number `0` is not used for the current hotkeys, it would be convenient to repurpose it to switch to the most recently used desktop.

### Windows Version

Windows 11

**Comment by dankrusi** [comment]
See v2.0 - has this feature

https://github.com/dankrusi/WindowsVirtualDesktopHelper/blob/main/Documentation/Hotkeys.md
