### ISSUE TITLE
[Bug]: Software breaks when switching to non-existant desktop with hot keys

### ISSUE THREAD

**Issue by camachomarco** [dankrusi/WindowsVirtualDesktopHelper#137]
### What happened?

When using hotkeys to switch to a given desktop (e.g., I use Left Alt+Shift+#), if you tap the number of a non-existent desktop, the software freezes for half a second, the overlay displays "Unknown," the taskbar disappears momentarily, and the software stops working (hotkeys become unresponsive until restart). I expected the software simply not do anything and remain functional when trying to switch to a non-existant desktop.

While this issue doesn't prevent users from using the software, I think it is worth mentioning.

### WVDH Version

v1.16

### Windows Version

Windows 11 23H2 build 22631.3085

**Comment by dankrusi** [comment]
thnx will fix

**Comment by yossdev** [comment]
hi @dankrusi, I was tinkering with the source and I think  I manage to fix this issue and added a few more things. Can I make a PR?
