### ISSUE TITLE
[Feature Request]: Window focus switch as you switch virtual desktops

### ISSUE THREAD

**Issue by camachomarco** [dankrusi/WindowsVirtualDesktopHelper#141]
### What feature?

I find this software very useful to switch between workspaces e.g. between code and browser. However, I have noticed that if I am coding and then I switch to the browser and decide to do something on the browser (e.g. Ctrl+L to edit the url) it will not work as the focus is still in the previous virtual desktop (my code editor). The forces me to use my mouse or to use Alt+Tab which defeats the purpose of using this software. 

By chance, I found some way to fix this by changing something in the windows registry that I can hardly remember but after an update from windows, this issue came back and the registry fix doesn't work anymore... 

This feature seems very important as without it, your workflow takes a **significant** hit in terms of efficiency and speed.

### Windows Version

Windows 11 23H2 build 22631.3085

**Comment by syeduroojkamal** [comment]
I found a better workaround, By activating "Activate a window by hovering over it with the mouse" option in the ease of use settings.

**Comment by camachomarco** [comment]
@syeduroojkamal Nice workaround! Unfortunately, on my end there is a small delay before the focus switches...but definitely better than nothing, thanks! Hopefully we can merge one of the PRs that have fixed this and focus switches instantly.

**Comment by dankrusi** [comment]
Fixed in 1.17
