### ISSUE TITLE
Virtual Desktop Helper not will not start[Bug]: 

### ISSUE THREAD

**Issue by haenf** [dankrusi/WindowsVirtualDesktopHelper#145]
### What happened?

I can't use Virtual Desktop Helper on my new laptop, at startup it instantly gives an error message (see below). Is there a way to make things working?

My Windows version is: Windows 11 Pro, build 22621.nl_release.220506-1250
Microsoft .NET Framework 4.8 is installed.

Hardware:
Processor: 13th Gen Intel(R) Core(TM) i9-13905H   2.60 GHz
Installed RAM	32,0 GB (31,7 GB usable)

Virtual Desktop Helper will not start, giving the following error message:

IsDarkThemeMode: could not get dark/light theme setting: Object reference not set to an instance of an object.
   at WindowsVirtualDesktopHelper.Util.OS.IsSystemLightThemeModeEnabled()
   at WindowsVirtualDesktopHelper.App.GetSystemThemeName()
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22631.3296
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.16.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_Insider22631

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22631.3296
GetImplementationForOS: Detected Windows 11 Insider Canary 22631 due to build >= 22631

### WVDH Version

1.16.0.0

### Windows Version

Windows 11 Pro, build 22621.nl_release.220506-1250

### Relevant log output

```shell
See above
```

**Comment by ladle3000** [comment]
Same for me

**Comment by Jhonatan-de-Souza** [comment]
also getting this same bug here

**Comment by dankrusi** [comment]
Does it work now with v1.17?
