### ISSUE TITLE
[Feature Request]:Don not display  The desktop number , only display the intital name of the desktop

### ISSUE THREAD

**Issue by calmwaves111** [dankrusi/WindowsVirtualDesktopHelper#149]
### What feature?

Displaying both the number and the initial name takes up a lot of space

### Windows Version

Windows 10

**Comment by dankrusi** [comment]
this is coming in 1.18

**Comment by dankrusi** [comment]
See in feature.showDesktopNumberInIconTray https://github.com/dankrusi/WindowsVirtualDesktopHelper/blob/main/Documentation/Settings.md
