### ISSUE TITLE
[Feature Request]: Ability to disable virtual desktop switching animation in windows 11

### ISSUE THREAD

**Issue by duyetnk** [dankrusi/WindowsVirtualDesktopHelper#150]
### What feature?

Add a checkbox or toggle to disable virtual desktop switching animation in windows 11

### Windows Version

Windows 11

**Comment by dankrusi** [comment]
Do you have a reliable registry key to make disable the Win 11 animation?

**Comment by duyetnk** [comment]
I don't know a registry key to disable switching animation
But I found a workaround using PowerToy and [VirtualDesktop](https://github.com/MScholtes/VirtualDesktop) like this:

![image](https://github.com/user-attachments/assets/647d3577-4ec7-4e5a-a9cf-f6708b2d7df9)

**Comment by dankrusi** [comment]
Can you see if adding a custom hotkey in v2.0 with Win+CTRL would also do the same thing for you?

https://github.com/dankrusi/WindowsVirtualDesktopHelper/blob/main/Documentation/Hotkeys.md

**Comment by duyetnk** [comment]
Yes, the new version has disabled the animation effect when switching screens. Thank you.
