### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ashish-bhardwaj-git** [dankrusi/WindowsVirtualDesktopHelper#151]
### What happened?

**### Reporting an issue I'm experiencing with focus behavior in Windows Virtual Desktop Helper**

I'm currently using your program to efficiently switch virtual desktops with hotkeys. However, I've encountered a problem where switching desktops doesn't automatically focus on the active window on the new desktop.

For example, if I'm working in Visual Studio Code on Desktop 1 and switch to Desktop 2 where I have Microsoft Word open, the focus remains on the previously active window in VS Code.  This requires me to manually switch focus to the Word window using  "Windows + Tab" or clicking on it directly.

I've checked the program settings to see if there are options related to focus behavior, but haven't found anything relevant.

I would be grateful if you could consider implementing a feature that automatically switches focus to the active window on the new desktop when switching virtual desktops. This would significantly improve my workflow and likely benefit other users as well.

### WVDH Version

1.16

### Windows Version

Windows 11 23H2

**Comment by MadoScientist97** [comment]
This was really bothering me as well, just raised a PR: https://github.com/dankrusi/WindowsVirtualDesktopHelper/pull/152
It would be helpful if you can test this build version and report back if this fixes it.

**Comment by ashish-bhardwaj-git** [comment]
> This was really bothering me as well, just raised a PR: #152 It would be helpful if you can test this build version and report back if this fixes it.

Is there any way you can send me the compiled program ?

**Comment by ashish-bhardwaj-git** [comment]
I appreciate your help, that definitely resolved the issue. Thanks a lot.

**Comment by ashish-bhardwaj-git** [comment]
Just a heads up, I'm experiencing an occasional glitch with the virtual desktop hotkeys. While the focus issue is resolved, [for example] sometimes hitting the hotkey for Desktop 4 sends me to Desktop 2 first.  A second press then correctly switches me to Desktop 4. It's not constant, but it's happening fairly frequently.
