### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by ArfersIorfik** [dankrusi/WindowsVirtualDesktopHelper#161]
### What feature?

The taskbar flashes,It will forcibly move the program to the taskbar of another desktop,Click the flashing taskbar icon,It will return to the desktop where the program is located,But this privacy is very bad,I hope to solve this problem,Even if you cancel flashing in the settings of WIN11,The problem still exists.

### Windows Version

WIN11

**Comment by dankrusi** [comment]
I don't understand what this has to do with WVDH - WVDH just facilitates switching a desktop and showing which desktop is active - the rest is all handled by windows...
