### ISSUE TITLE
The color of icons don't change when the theme of windows changes.

### ISSUE THREAD

**Issue by lcx-0504** [dankrusi/WindowsVirtualDesktopHelper#17]
I love this software. It really helps me a lot. Thank you very much. But the color of icons don't change when the theme of windows changes. I use "auto dark mode" to switch windows theme automatically, so I can use light mode in daytime and use dark mode in night. However, your software doesn't change the color of icons, so I must exit software and reopen it to make sure it displays in right color. I would be appreciate if you can solve this problem.
Your friends from China.😊

**Comment by dankrusi** [comment]
Hi @lcx-0504, thanks for the tip - indeed the icons should detect a theme change. I will add this in the next version. Greetings from Switzerland, -dan

**Comment by lcx-0504** [comment]
Thank you very much😉

**Comment by dankrusi** [comment]
Fixed in v1.10. Best
