### ISSUE TITLE
Remembering Settings

### ISSUE THREAD

**Issue by maciekbeee** [dankrusi/WindowsVirtualDesktopHelper#18]
Hi,
I love the helper. 
In my case, settings are not remembered after system restart.
Windows 10 Pro, 10.0.19045 Build 19045
Version 1.9
![my set](https://user-images.githubusercontent.com/122607803/212303804-b016306d-8d62-41e5-81e1-2cf7537e6bae.jpg)
![after res](https://user-images.githubusercontent.com/122607803/212303807-34a13828-8c10-4f1b-bca0-3b7f3f542076.jpg)
Thanks!

**Comment by dankrusi** [comment]
Thanks @maciekbeee , I will look into this soon.

**Comment by Tsaukpaetra** [comment]
It appears to be using its own program folder or machine-level settings. If I open as Administrator it can save as expected.
Likely should just move the settings into the user settings store instead of the application store.

**Comment by maciekbeee** [comment]
Thanks! Two things. 

One – temporarily I set the EXE to admin, so it remembered settings, but it could not start automatically with Windows. When I switched off admin rights, it starts with Windows and settings stayed mine. It's enough for me.

Two – I installed via your MSI installer. It installs to 
C:\Program Files (x86)\Windows Virtual Desktop Helper
My user profile is admin, but as we can see, the program cannot change its settings.

Like you mentioned, perhaps, if I used EXE from your ZIP, I would save it to my user folder, so it would work fine.
The message is – using the MSI leads to settings block.

If I would like to change this, can I just move the folder with your program, or should I uninstall and then use the ZIP version?

**Comment by dankrusi** [comment]
> If I would like to change this, can I just move the folder with your program, or should I uninstall and then use the ZIP version?

If you use the ZIP version with local (user) rights you should be fine. Or update to v1.10

**Comment by TTSKarlsson** [comment]
The problem is still there and due to the app being installed in the installers default location (`Program Files(x86)`) which is a protected location, and that the config is saved to same directory. The config should be stored in `%APPDATA%\<appname>\` or the default install location should be outside the protected directories.

Installing this to `D:\apps\windowsvirtualdesktophelper\` fixed the problem for me.
