### ISSUE TITLE
Windows Installer Update not possible

### ISSUE THREAD

**Issue by chrisonline** [dankrusi/WindowsVirtualDesktopHelper#19]
I have just downloaded the newest version to update, but I get this error if I want to update it:
<img width="273" alt="image" src="https://user-images.githubusercontent.com/2077218/213697362-4ccb5557-918b-4b8e-a615-3fb478e6fe8b.png">

It means "Another version of this product is already installed... You need to uninstall the product first".

Is there no update feature? Do I need to uninstall always before?

**Comment by dankrusi** [comment]
Sorry, forgot to update the version number on the installer. Try again (download the MSI again). Best
