### ISSUE TITLE
Virustotal found some viruses

### ISSUE THREAD

**Issue by isheev** [dankrusi/WindowsVirtualDesktopHelper#2]
Hi. I want to try this app. But before, I checked it on Virustotal.com.
It says there some viruses. I hope it is a mistake, and you can fix it.
![image](https://user-images.githubusercontent.com/34710210/202694481-ec1c73d4-ad67-4f8c-b4ce-5d7910083d76.png)

**Comment by dankrusi** [comment]
Hi, 

Unfortunately this is a false positive for the free installer I use (Inno Setup, see https://jrsoftware.org/isinfo.php), and because I don't (yet) code-sign the app and installer (its expensive to do so). See FAQ.

If you use the ZIP version (without the installer), you will be fine.

Best,

-dan

**Comment by isheev** [comment]
I just tried to run it from cmd and nothing appeared in the tray. Am i doing something wrong?
![image](https://user-images.githubusercontent.com/34710210/202698800-c4b85011-21e1-4a4e-a508-dc5f49f8aa4f.png)

**Comment by dankrusi** [comment]
Which version of Windows?

**Comment by isheev** [comment]
Edition	Windows 11 Pro
Version	22H2
Installed on	‎04.‎11.‎2022
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by dankrusi** [comment]
Thanks. And you do have Microsoft .NET installed?

**Comment by isheev** [comment]
Yes. I have installed .NET6

**Comment by dankrusi** [comment]
Do you see any errors in the Windows Events logs? Like in this issue here https://github.com/dankrusi/WindowsVirtualDesktopHelper/issues/1?

**Comment by dankrusi** [comment]
The original installer Inno Setup has been removed. A standard Microsoft setup is now included.

![image](https://user-images.githubusercontent.com/190233/203587962-b7667324-4df7-454d-8415-8a06107f88e0.png)


Regarding the Windows 11 issue, see https://github.com/dankrusi/WindowsVirtualDesktopHelper/issues/1 for further issue tracking.
