### ISSUE TITLE
Error: IsDarkThemeMode: could not get dark/light theme setting: 未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by x-bytes** [dankrusi/WindowsVirtualDesktopHelper#20]
IsDarkThemeMode: could not get dark/light theme setting: 未将对象引用设置到对象的实例。
   在 WindowsVirtualDesktopHelper.Util.OS.IsSystemLightThemeModeEnabled()
   在 WindowsVirtualDesktopHelper.App.GetSystemThemeName()
   在 WindowsVirtualDesktopHelper.App..ctor()
   在 WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 17763
Windows Release: 1809
Windows Product: Windows 10 Enterprise LTSC 2019
Windows Version: 
Windows Virtual Desktop Helper Version: 1.10.0.0
Virtual Desktop Implementation: VirtualDesktopWin10

Log:
GetImplementationForOS: Windows Build Version: 17763
GetImplementationForOS: Fallback to Windows 10 (fallback)
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: success!

**Comment by dankrusi** [comment]
Hi, please update to the latest version and re-open a issue if the problem still persists. Thanks!
