### ISSUE TITLE
FR: Keyboard shortcuts to directly access specific desktop

### ISSUE THREAD

**Issue by topnik-code** [dankrusi/WindowsVirtualDesktopHelper#21]
Thank you so much for this tool, this is insanely helpful! 💜

Not sure if this is possible, but things that would make this even better:

- Keyboard shortcuts to directly jump to a specific virtual desktop
- Keyboard shortcut to send the current window to a specific virtual desktop

Best regards!

**Comment by dankrusi** [comment]
Hi, thanks for your ticket.

I think this goes beyond the scope of this app. For this functionality you can expect Windows 11 to eventually have more desktop management features, or use other 3rd party apps.

Best,

-dan
