### ISSUE TITLE
The both overlay and taskbar indicators won't change if wake up from sleep.

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [dankrusi/WindowsVirtualDesktopHelper#23]
It is like, leave the computer to sleep 1-2 days and then wake it up, the indicators won't change unless I restart the program.

**Comment by dankrusi** [comment]
Hi @JaneValleyhasBtaken ,
Thanks for this ticket. Can you investigate further - I can't reproduce this. What hardware and win ver?
-dan

**Comment by JaneValleyhasBtaken** [comment]
My windows version is 22623.1325, running on a Surface Laptop 3 intel processor.
I will try if I can get further information about this

**Comment by JaneValleyhasBtaken** [comment]
OK I can't reproduce this issue any more,... Closed for now
