### ISSUE TITLE
I don't immediately know the name of the desktop.

### ISSUE THREAD

**Issue by d-kawakawa** [dankrusi/WindowsVirtualDesktopHelper#27]
Hello, I am new to commenting on github.
I'm a Japanese Windows user.
(Sorry, this English sentence is Google translation from Japanese)

I read the introductory article on this page and started using "Virtual Desktop Helper".

https://forest.watch.impress.co.jp/docs/review/1476689.html

Please consider the following as one of your opinions.

When I wake the computer from sleep and try to resume work, I don't immediately know the name of the desktop.
The current version shows a number in the taskbar,

![fig3](https://user-images.githubusercontent.com/126934692/222874635-32323edf-59fe-4978-98e0-9ddd272df2cf.png)

but I'd like to see the name of the virtual desktop displayed somewhere if possible.
(Sorry if this was already planned.)
thank you.

**Comment by tucan555** [comment]
Hi, this is an almost perfect utility, it just works!

All I would like to see is an option to show the desktop NAME in the taskbar as well as or in place of the desktop number shown currently.

**Comment by dankrusi** [comment]
Hi,

Windows doesn't support text-based notification icons in the notification tray. The only way one can do it (officially), is to create a icon dynamically with text in it, but of course the space is very limited and such a feature would be very questionable. I might consider allowing an option for the first two characters of the desktop name, if other people want this too.

The next version will have a tooltip:

![image](https://user-images.githubusercontent.com/190233/225876478-cb5c63c2-e67e-402e-9e7b-938bf7eacddf.png)

Best,

-dan

**Comment by dankrusi** [comment]
PS: An alternate solution to your problem would be to show the notification screen on wake. I will look into this.

-dan

**Comment by dankrusi** [comment]
See https://github.com/dankrusi/WindowsVirtualDesktopHelper/issues/30

**Comment by tucan555** [comment]
Hi Dan, 
The tooltip would be useful but the two letters icon in the toolbar would be much better as it doesn't need any user input to display the 'name'. I think the additional idea for the letters to be the first letter of two words is a really good one.

Thanks in advance for this feature!

**Comment by dankrusi** [comment]
Hi @tucan555 ,

See 
[WindowsVirtualDesktopHelper Executable v1.11.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/11572422/WindowsVirtualDesktopHelper.Executable.v1.11.zip)
