### ISSUE TITLE
FR: Option to only show '#' instead of 'Desktop #'

### ISSUE THREAD

**Issue by oxysoft** [dankrusi/WindowsVirtualDesktopHelper#28]

**Comment by oxysoft** [comment]
I can implement this if you want, should be pretty quick and easy!

**Comment by dankrusi** [comment]
Hi @oxysoft,

Thanks - however I think the current solution is simpler and more universal - the notification just shows the name of the Virtual Destkop. If you just want it to show "2", then you can just rename your Virtual Desktop to this instead of "Desktop 2".

Best,

-dan

**Comment by oxysoft** [comment]
Ahhhhhh I didn't know workspaces had a name and you were simply displaying it, in that case I fully understand.

I have a ahk script which automatically creates 9 workspaces on startup, I will see if I can do the renaming there automatically instead!
