### ISSUE TITLE
FR: Delay before UI appearing?

### ISSUE THREAD

**Issue by oxysoft** [dankrusi/WindowsVirtualDesktopHelper#29]
It seems like there is a delay before the UI appears after switching desktop. I would prefer it it were visible as soon as I hit the shortcut like on linux, but I suspect there may be some limitation or interaction with the switching animation that made this necessary. If that's the case, I think we should still offer the option for users who disabled the animation!

**Comment by dankrusi** [comment]
Hi @oxysoft ,

Thanks for your issue/FR contributions. 

Regarding the delay, there shouldn't be one above 100ms. The way the app works, is that it polls a Windows API for the current desktop number, and if it detects a switch then it updates the UI etc... Note that the Windows click event on a notification icon also has a delay, as it waits for the mouse release and to find out if there will be a double-click...

The idea for the app is to have a very simple and leightweight Windows integration, as these APIs are constantly changing and must be customized for almost every build MS releases. Thus I don't want to change the polling mechanism at this point. 

If you want, you can build your own version with a polling mechanism of 10ms, but I don't think this is something all users need (think of people on battery).

Finally, if the delay is more than 100ms for you, then you will need to debug what is causing the notification window of taking so long to show up. Maybe you have some unofficial window manager stuff installed?

Best,

-dan
