### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by norbou2** [dankrusi/WindowsVirtualDesktopHelper#31]
Hello Dan, 
I liked this app, but I have some problems with reliability. OSD did not show after few hours of testing and I have noticed app hangs (Application or service 'Windows Virtual Desktop Helper' could not be shut down.). But after some days explorer has begun crash every day, especially when I click on the taskview switcher icon:

Faulting application name: Explorer.EXE, version: 10.0.22621.1344, time stamp: 0x7e4082a9
Faulting module name: WindowsInternal.ComposableShell.Experiences.Switcher.dll, version: 10.0.22621.1344, time stamp: 0x9a51a0de
Exception code: 0xc0000005
Fault offset: 0x0000000000050dbf
Faulting process id: 0x0x286C
Faulting application start time: 0x0x1D970F67567800D
Faulting application path: C:\WINDOWS\Explorer.EXE
Faulting module path: C:\Windows\ShellComponents\WindowsInternal.ComposableShell.Experiences.Switcher.dll
Report Id: bc14d9eb-b74a-4298-9a4c-0f57d612da30

****
The shell stopped unexpectedly and explorer.exe was restarted.
****

Fault bucket 1952542367184157302, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Explorer.EXE
P2: 10.0.22621.1344
P3: 7e4082a9
P4: WindowsInternal.ComposableShell.Experiences.Switcher.dll
P5: 10.0.22621.1344
P6: 9a51a0de
P7: c0000005
P8: 0000000000050dbf
P9: 
P10: 

Attached files:
[\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7d32e2ed-9923-4af4-a21e-87d8fb09adba.tmp.WERInternalMetadata.xml](file://%3F/C:/ProgramData/Microsoft/Windows/WER/Temp/WER.7d32e2ed-9923-4af4-a21e-87d8fb09adba.tmp.WERInternalMetadata.xml)

These files may be available here:
[\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Explorer.EXE_28527a65dd710d361e5955328a15cbcd560a8c8_90e6c4f8_c73c4169-eb33-4a6c-96ae-a122eb874d7d](file://%3F/C:/ProgramData/Microsoft/Windows/WER/ReportArchive/AppCrash_Explorer.EXE_28527a65dd710d361e5955328a15cbcd560a8c8_90e6c4f8_c73c4169-eb33-4a6c-96ae-a122eb874d7d)

Analysis symbol: 
Rechecking for solution: 0
Report Id: 820821ef-7bcc-4442-aa18-60706209872b
Report Status: 268435456
Hashed bucket: 4f3261b07741539fab18d2f01ce97a76
Cab Guid: 0

Does have anybody same problem and solution?
How can I ensure that helper was fully uninstalled?

Thank you,
Jiri

**Comment by dankrusi** [comment]
Hi @norbou2 , sorry for your troubles. 

What OS Version are you on and which version of the app?

I don't think your explorer issues are related to WVDH - its just a simple app with a series of notification icons - no hooks or Explorer modifications. It's all C# and Microsoft APIs...

I've designed the app to be very simple and lightweight. It doesn't need to be installed and doesn't need any requirements (other than .NET framework, which is part of Windows standard installation). You just need the WindowsVirtualDesktopHelper.exe.

Best,

-dan
