### ISSUE TITLE
FR: switch desktop with WIN+CTRL+Mouse Wheel

### ISSUE THREAD

**Issue by sardoinside** [dankrusi/WindowsVirtualDesktopHelper#33]
Can we have a new functionality that allows, through the typing of Win+Ctrl+mouse wheel, change the virtual desktop used?
It would really be an excellent feature that would allow you to change desktop without leaving your hands from the mouse and without having to click in a specific point of the screen.
Thanks for the work done so far, it is excellent and useful

**Comment by dankrusi** [comment]
Hi @sardoinside , thanks for the suggestion, however I think this feature would be beyond the scope of the app. There are other apps that specialize in keyboard shortcuts. Maybe you can take a look at one of those. If I add this feature, it would open a flood of other customizations and features. I want to avoid feature-creep.
