### ISSUE TITLE
Error: LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10

### ISSUE THREAD

**Issue by waldimen** [dankrusi/WindowsVirtualDesktopHelper#35]
After upgrade of windows 11 I got following error:

I am connected to  Windows Insider Programme in Dev channel. 

```

LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 23466
Windows Release: 2009
Windows Product: Windows 10 Pro
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.10.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_22H2

Log:
GetImplementationForOS: Windows Build Version: 23466
GetImplementationForOS: Detected Windows 11 22H2 due to build >= 22621
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by javiergarciad** [comment]
Same here!

**Comment by dankrusi** [comment]
Hi @waldimen , @javiergarciad ,

Does this version work for you?

Best,

-dan

[WindowsVirtualDesktopHelper Executable v1.11.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/11572170/WindowsVirtualDesktopHelper.Executable.v1.11.zip)

**Comment by zobbo** [comment]
@dankrusi I am also on the insider build with the same error. Many thanks for taking a look at this so quickly. The new file gives me the following when I try to run it 

```

LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 23466
Windows Release: 2009
Windows Product: Windows 10 Home
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.11.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_22H2

Log:
GetImplementationForOS: Windows Build Version: 23466
GetImplementationForOS: Detected Windows 11 22H2 due to build >= 22621
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by dankrusi** [comment]
Can some try and see if this works for them (VirtualDesktopInsider.exe)? https://github.com/MScholtes/VirtualDesktop/releases/tag/V1.12

This would let me know if somehow has figured out the API entry points yet...

**Comment by dankrusi** [comment]
@zobbo - thanks. Damn I'm not sure if someone has reverse engineered your version yet. I will try to find out the GUID for the API calls, but it will take a while...

**Comment by javiergarciad** [comment]
V 1.12 not working on this machine. 

OS Name	Microsoft Windows 11 Pro Insider Preview
Version	10.0.23466 Build 23466
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	LATITUDE
System Manufacturer	Dell Inc.
System Model	Latitude 7390
System Type	x64-based PC
System SKU	081B
Processor	Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.30.0, 20/11/2022
SMBIOS Version	3.1
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0C50DC
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.23466.1001"
User Name	LATITUDE\Javier
Time Zone	SA Pacific Standard Time
Installed Physical Memory (RAM)	16,0 GB
Total Physical Memory	15,9 GB
Available Physical Memory	5,12 GB
Total Virtual Memory	31,9 GB
Available Virtual Memory	17,5 GB
Page File Space	16,0 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, DMA Protection, UEFI Code Readonly, Mode Based Execution Control
Virtualization-based security Services Configured	Hypervisor enforced Code Integrity
Virtualization-based security Services Running	Credential Guard, Hypervisor enforced Code Integrity
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by waldimen** [comment]
Hello, 

I got following error when I tried to run:

`VirtualDesktopInsider.exe /list`

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception. ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop.DesktopManager..cctor()
   --- End of inner exception stack trace ---
   at VirtualDesktop.Desktop.get_Count()
   at VDeskTool.Program.Main(String[] args)
```

**Comment by zobbo** [comment]
Not sure if this helps at all as although I'm a programmer of 35 years, the arcane world of windows is outside of my current remit (thankfully!)

https://github.com/MScholtes/VirtualDesktop/issues/46

The issue there has a comment:

```I'm tired of cat-and-mouse game with Microsoft. I've made a script to download and analyze PDB symbols to automatically extract GUID and some COM method.```

and a link to https://github.com/NyaMisty/GetVirtualDesktopAPI_DIA

I am a python programmer (but not normally on windows). If it aids the quest I can try and get it running and see what it says although once again, I'm not sure if this a red herring!

Missing your little utility at the moment! :)

Ian

**Comment by dankrusi** [comment]
@zobbo , perfect thanks! Yes please do run it and let me know. I will provide you a build. Later when I have time I will try to integrate this technique into the app itself so that you can automatically submit the data to me. Best, -dan

**Comment by snoroozi** [comment]
Also on win11 release preview channel for insider builds.  App is crashing once in a while and just restarting it makes it work for a while.  I'll copy the error here next time I see it.

I did notice before the first time it happened, it showed I was on a different window number then I was really on, then moments later crashed for the first time.

**Comment by zobbo** [comment]
Surprised restarting makes it work for you as it just totally dies here. I'm currently stuck with the util I was looking at to try and help with the debugging. I can't seem to get it to run because of the dll registration error I noted last week. Somebody else has the same issue. If any windows programmers have any insights I'd greatly appreciate it.

**Comment by MScholtes** [comment]
Microsoft did a strange thing with Windows 11 Insider Dev: they lowered the build number from 25309 to 23403 on March 8, 2023. That's weird.

Version checking might need to be corrected.

**Comment by dankrusi** [comment]
@MScholtes thanks for the heads up. This is updated in [v1.11](https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/tag/v1.11), however since the app uses a fallback system where it tries every implementation possible, it shouldn't fix the issue for insider dev users...

**Comment by zobbo** [comment]
Confirmed, no change for the insider dev users

**Comment by rldourado** [comment]
@dankrusi , v1.12 **worked** for me.

My Windows 11 version:

![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/2440820/c4195f15-7652-4462-8b9b-685ea8d84910)

Windows 11 Pro Version 22H2 Build 22621.2215
