### ISSUE TITLE
Compatibility with ExplorerPatcher

### ISSUE THREAD

**Issue by koppor** [dankrusi/WindowsVirtualDesktopHelper#37]
On Windows 11, the [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) makes work more pleasant.

However, when switching desktops, the number displayed by WindowsVirtualdDesktopHelper does not update.

**Comment by dankrusi** [comment]
Is this still the case with v2.0?

**Comment by koppor** [comment]
I will check - and reopen if the issue persists.
