### ISSUE TITLE
Display Full Desktop Name on Screen

### ISSUE THREAD

**Issue by stewartbholt** [dankrusi/WindowsVirtualDesktopHelper#38]
I have a multiple large monitors and rarely maximize windows so there are almost always areas of the screen background visible, It would be very nice if the full desktop name could appear over the screen background of the primary display with options to locate it in one of the 4 corners. I recently started using the taskbar hide mode so to see the desktop initial, I have to mouse to the bottom or hit the Win key to see it.

**Comment by dankrusi** [comment]
Hi @stewartbholt ,

What do you mean exactly? This feature already exists... "Show overlay when switching Desktop"

Best,

-dan
