### ISSUE TITLE
Error: LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10

### ISSUE THREAD

**Issue by skyblue-jpn** [dankrusi/WindowsVirtualDesktopHelper#40]
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22631
Windows Release: 2009
Windows Product: Windows 10 Home
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.11.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_22H2

Log:
GetImplementationForOS: Windows Build Version: 22631
GetImplementationForOS: Detected Windows 11 22H2 due to build >= 22621
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10

**Comment by dankrusi** [comment]
Hi, does v1.12 fix you issue? https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/tag/v1.12

**Comment by YaoLei-Leo** [comment]
The v1.12 fixs this. Thank you @dankrusi .
