### ISSUE TITLE
New changes...

### ISSUE THREAD

**Issue by y2nd66** [dankrusi/WindowsVirtualDesktopHelper#42]
several changes in 11 23H2, from build 2050

[https://github.com/y2nd66/WindowsVirtualDesktop/blob/main/11.22631.2115/11.22631.2115.txt](https://github.com/y2nd66/WindowsVirtualDesktop/blob/main/11.22631.2115/11.22631.2115.txt)

all data in
[11.22631.2115_all.zip](https://github.com/y2nd66/WindowsVirtualDesktop/blob/main/11.22631.2115/11.22631.2115_all.zip)

**Comment by y2nd66** [comment]
I'd like create a pull request with fix for >= 11.226x1.2050

**Comment by dankrusi** [comment]
Awesome, thanks - but I don't see the pull request...?

**Comment by y2nd66** [comment]
sorry i didn't make it

something with the permissions prevents me from creating a pull request

[here are the changes](https://github.com/dankrusi/WindowsVirtualDesktopHelper/compare/main...y2nd66:WindowsVirtualDesktopHelper:y2nd66)

**Comment by y2nd66** [comment]
now...yes
