### ISSUE TITLE
Error: LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10

### ISSUE THREAD

**Issue by togotom** [dankrusi/WindowsVirtualDesktopHelper#54]
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   bei WindowsVirtualDesktopHelper.App..ctor()
   bei WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22621
Windows Release: 2009
Windows Product: Windows 10 Pro for Workstations
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.11.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_22H2

Log:
GetImplementationForOS: Windows Build Version: 22621
GetImplementationForOS: Detected Windows 11 22H2 due to build >= 22621
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10

**Comment by dankrusi** [comment]
Hi, does v1.12 fix you issue? https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/tag/v1.12

**Comment by togotom** [comment]
Thanks for the quick help, the new version 1.12 runs again without problems.

**Comment by dankrusi** [comment]
You are on Windows Insider right?

**Comment by togotom** [comment]
This is the Update that i installed yesterday

https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

**Comment by togotom** [comment]
Now with the Vesion WindowsVirtualDesktopHelper.Setup.v1.14.msi everything runs correctly again. Thanks for the fast Updates.
