### ISSUE TITLE
FR: add option to specify overlay duration and position

### ISSUE THREAD

**Issue by WhiteNoiseDev** [dankrusi/WindowsVirtualDesktopHelper#6]

**Comment by dankrusi** [comment]
the duration is planned. what position options do you envision?

**Comment by dankrusi** [comment]
The duration is in version 1.5

**Comment by dankrusi** [comment]
@WhiteNoiseDev, what do you think about this RE position?
[WindowsVirtualDesktopHelper.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/10146203/WindowsVirtualDesktopHelper.zip)
![image](https://user-images.githubusercontent.com/190233/205437395-02793e8f-0b4f-45c2-91fb-5e9c67fd224c.png)

**Comment by owainbytangram** [comment]
Getting a Wacatac.H!ml virus warning with this file.

**Comment by WhiteNoiseDev** [comment]
I am getting virus warning as well. nevertheless it works.
There is a bug: the duration selectors are tied to the position selectors.

**Comment by owainbytangram** [comment]
This is a good suggestion though. Thanks @dankrusi for looking into it. The proposed solution is what I came here to open a request for. Windows implementation (lack of) for Virtual Desktops has always bothered me a little as I was used to using them on Linux with more flex

**Comment by dankrusi** [comment]
@owainbytangram @WhiteNoiseDev  RE malware warning: its a bit difficult these days to publish such exes which use Windows APIs (like the Virtual Desktops) or Registry Edits (Autostart with windows feature). Once the app is a bit more stable I will get in touch with the Windows Defender team. I would sign the executable, but its very expensive with a yearly fee... 
What drives me crazy is that if I scan the original ZIP file with Windows Defender, there is no warning. If I download it from GitHub, it gives me Wacatac.H!ml warning. When I scan the ZIP from github with VirusTotal I don't get any warning...
![image](https://user-images.githubusercontent.com/190233/205485049-11c89b14-ab2d-416c-b8a2-dd9695ec36a1.png)

**Comment by dankrusi** [comment]
> I am getting virus warning as well. nevertheless it works. There is a bug: the duration selectors are tied to the position selectors.

Thanks. Fixed in v1.6
