### ISSUE TITLE
I wish to be able to change the color of the taskbar buttons to white.

### ISSUE THREAD

**Issue by lan5635** [dankrusi/WindowsVirtualDesktopHelper#66]
well  This is the current style
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/10723912/dc69514b-15c2-489e-9499-f225aa67dbf0)
I would like to be able to customize the color of these three buttons 
or be able to switch to white

**Comment by lan5635** [comment]
thank U all

**Comment by dankrusi** [comment]
Hi @lan5635,

Doesn't the UI switch automatically between white and black, depending on what windows dark mode theme is currently set?

**Comment by lan5635** [comment]
The tray area does switch automatically depending on the dark/light color of the system, which is an issue on my end

**Comment by dankrusi** [comment]
I'm confused - the icons of WVDH should always take on the color defined by the current Windows light/dark theme, matching the other system icons in the tray area. In your screenshot this is not the case, however I cannot reproduce the issue. Is this always happening on your system, or only under certain circumstances?
