### ISSUE TITLE
FR: the overlay should not have focus

### ISSUE THREAD

**Issue by WhiteNoiseDev** [dankrusi/WindowsVirtualDesktopHelper#7]
While switching desktop the overlay has focus, so I have to wait for it to go away to start typing.

**Comment by dankrusi** [comment]
fixed in https://github.com/dankrusi/WindowsVirtualDesktopHelper/commit/ded1c8cfd7cd009b8c6cbab3461fcf4d13c3b780

**Comment by dankrusi** [comment]
See version 1.5

**Comment by dankrusi** [comment]
FYI @WhiteNoiseDev this improves on this ticket as well https://github.com/dankrusi/WindowsVirtualDesktopHelper/commit/6b33b18c6205167ea6aeaee9629ceac24cbaa40a
Will be in next version
