### ISSUE TITLE
FR: Custom taskbar color for each desktop

### ISSUE THREAD

**Issue by Giulidan** [dankrusi/WindowsVirtualDesktopHelper#78]
First of all, thank you for such useful software, with functionalities that are expected to come with Windows already... anyways.

Would it be possible to have custom taskbar color for each desktop? I don't know how hard would it be to implement it, but I'd find it very useful because I could distinguish easily in which desktop I am.

Thank you!

PS: I have more suggestions, do I create an issue for each one?

**Comment by dankrusi** [comment]
@Giulidan, thanks!

The idea of the app is too keep it as simple and basic as possible, integrating smoothly into the windows UI. I want to avoid bloating the app with features and settings, and more focus on keeping it compatible with Windows (a touch job - as the APIs are not public/official).

In the future I might add a bunch of command line options or hidden settings one can tweak, but it will take a few months until I have time.

Feel free to add suggestions.

Best,

-dan
