### ISSUE TITLE
Error: LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10

### ISSUE THREAD

**Issue by yonggeun** [dankrusi/WindowsVirtualDesktopHelper#82]
Hi, 
I have this message every time when I restart the app. 
Luckily, I can post the issue via the app. 
Thank you. 

LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_22H2,VirtualDesktopWin11_Insider,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22621
Windows Release: 2009
Windows Product: Windows 10 Home Single Language
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.10.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_22H2

Log:
GetImplementationForOS: Windows Build Version: 22621
GetImplementationForOS: Detected Windows 11 22H2 due to build >= 22621
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10

**Comment by viniciusccosta** [comment]
@yonggeun In my case, I was not even able to manually start the app. So, I just installed the [last version](https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/download/v1.14/WindowsVirtualDesktopHelper.Setup.v1.14.msi) of the app and it started to work again. Not sure if it's going to keep working after reboot, but for now, it's working again.

**Comment by dankrusi** [comment]
Hi, please update to the latest version of the app first. Kind regards, -dan
