### ISSUE TITLE
Error: LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10

### ISSUE THREAD

**Issue by jarusaurus** [dankrusi/WindowsVirtualDesktopHelper#83]
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 25941
Windows Release: 2009
Windows Product: Windows 10 Pro
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.10.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_Insider

Log:
GetImplementationForOS: Windows Build Version: 25941
GetImplementationForOS: Detected Windows 11 Insider due to build 25158-5267
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10

**Comment by viniciusccosta** [comment]
@jarusaurus In my case, I was able to fix it just installing the [last version](https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/download/v1.14/WindowsVirtualDesktopHelper.Setup.v1.14.msi) of the app!

**Comment by jarusaurus** [comment]
Oh, thanks much for that. Yes, it did fix up. Thanks to the dev again.
