### ISSUE TITLE
New feature ideas

### ISSUE THREAD

**Issue by pablonosh** [dankrusi/WindowsVirtualDesktopHelper#85]
Hi

This is great.
Could I suggest the option of showing the overlay indefinitely?
and on a similar bent the option of showing the whole name in the taskbar?

Thanks

**Comment by frankhommers** [comment]
I'd like the indefinite option as well. It could be a transparent window, and once you approach it with the mouse, it could shortly disappear or move elsewhere.

**Comment by dankrusi** [comment]
this is coming in 1.18

**Comment by dankrusi** [comment]
``feature.showDesktopSwitchOverlay.duration: 2000 #Defines the duration in milliseconds for a switch overlay to show. If set to zero, then the overlay is shown indefinately.``
