### ISSUE TITLE
[Feature Request] Scoop Package

### ISSUE THREAD

**Issue by adamency** [dankrusi/WindowsVirtualDesktopHelper#86]
I know there's already #8 which talks about winget and choco.

However, `scoop` (https://github.com/ScoopInstaller/Scoop) is the only actual package manager in Windows, meaning it actually installs the package from the command line and stores executables in known places. This project would gain a lot to be available in `scoop`.

Please consider it :)

Thanks a lot for your project !

**Comment by dennisroche** [comment]
- [x] create `mainfest.json` base
- [ ] generate `sha512` hashes to verify updates as part of release
- [ ] update `manifest.json` with SHA
- [ ] open PR on Scoop Extras

https://github.com/ScoopInstaller/bucket/windows-virtualdesktop-helper.json

```json
{
  "version": "1.15",
  "description": "App to help manage Virtual Desktops for Windows 10 and Windows 11.",
  "homepage": "https://github.com/dankrusi/WindowsVirtualDesktopHelper",
  "license": "GPL-3.0-only",
  "architecture": {
    "64bit": {
      "url": "https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/download/v1.15/WindowsVirtualDesktopHelper.Executable.v1.15.zip",
      "hash": "todo"
    }
  },
  "bin": "WindowsVirtualDesktopHelper.exe",
  "shortcuts": [
    [
      "vdhelper.exe"
    ]
  ],
  "checkver": {
    "github": "https://github.com/dankrusi/WindowsVirtualDesktopHelper"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/download/v$version/WindowsVirtualDesktopHelper.Executable.v$version.zip",
        "hash": {
          // todo
        }
      }
    }
  }
}
```

**Comment by adamency** [comment]
Thanks a lot ! I can look into doing the work for the last 3 steps if you want :)

**Comment by dankrusi** [comment]
Thanks, as long as it doesn't require the EXE to be signed, I can add Scoop support.

**Comment by padd1er** [comment]
Nope, it does not require signed exe. At least I'm not aware of such requirement and it's not mentioned in scoop wiki.

Already using simplified "half manual" approach within my personal scoop bucket, but would greatly appreciate the official manifest with automated updates in extra bucket of scoop.


```
{
    "##": "This file is a template. Fill the blanks and add or remove fields as necessary.",
    "version": "1.16",
    "description": "Simple and lightweight app to help with Virtual Desktops for Windows 10 and Windows 11.",
    "homepage": "https://github.com/dankrusi/WindowsVirtualDesktopHelper",
    "license": "GPL-3.0-only",
    "url": "https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/download/v1.16/WindowsVirtualDesktopHelper.Executable.v1.16.zip",
    "shortcuts": [
        [
            "WindowsVirtualDesktopHelper.exe",
            "WindowsVirtualDesk"
        ]
    ]
}
```

**Comment by dankrusi** [comment]
Main documentation URL for contributing to Scoop:

https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md

We will use Scoop Extras: https://github.com/ScoopInstaller/Extras, forked at: https://github.com/dankrusi/Scoop-Extras/tree/app/windows-virtualdesktop-helper

Main Steps:

- [x] Fork the repository and create a new branch from the default branch (usually master), with an appropriate name.
- [x] Write your code. Follow these guidelines for writing manifests:
- [x] Test your manifest by installing, uninstalling, checking functionality, persistence etc.
- [x] Confirm that manifest gets updated automatically - see [App Manifest Autoupdate](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate).
- [x] Submit your pull request. Titles should follow these rules:
- [x If it's a new manifest, use <app name>: Add version <version>.
- [ ] If it's an update to an existing manifest, use <app name>@<version>: <small description>.
- [ ] If it's something related to maintenance, use (chore): <small description>.
- [x] Add a comment starting with "/verify" after raising the PR - this will kick in the automatic manifest verifier.
- [ ] Wait for code review and address any issues raised as soon as you can.

PR @ Scoop: https://github.com/ScoopInstaller/Extras/pull/12724

**Comment by dankrusi** [comment]
@adamency @padd1er @dennisroche you're welcome ;)

https://github.com/ScoopInstaller/Extras/pull/12724#event-11660114376
