### ISSUE TITLE
Enhancement Idea Please

### ISSUE THREAD

**Issue by ComputerCulture** [dankrusi/WindowsVirtualDesktopHelper#88]
Hi @dankrusi 
Thank you for your work, and very useful software.
Just asking if this idea would be possible to add to the settings menu as an option.
Using keybindings to move to new virtual desktops.
This would be really quick way to switch around the users workspace.

Example, 
Switch to virtual workspace 1 - Alt 1
Switch to virtual workspace 2 - Alt 2
Switch to virtual workspace 3 - Alt 3
Switch to virtual workspace 4 - Alt 4

Kind regards
CC

**Comment by ComputerCulture** [comment]
Hi Dan,
Just adding an example of what i was talking about, adding this feature to the settings if possible. Thank you.

![Example](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/133943765/338a505d-c8e7-4117-b626-d7eee379e319)

**Comment by ComputerCulture** [comment]
Hi @dankrusi 

Just wanted to say  thank you for the hard work you put into your software.
Well done... Cheers

Regards
CC

**Comment by dankrusi** [comment]
thnx
